### ISSUE TITLE
App switcher has hard coded icon

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#342] opened 2018-06-22 16:12 UTC
**Describe the bug**
App switcher assumes the icon for the switcher: https://github.com/HealthCatalyst/Fabric.Cashmere/blob/1ab3f38e77d1623ebf6d00205cdc490b531430dd/projects/cashmere/src/lib/app-switcher/app-switcher.component.html#L8

```html
<div #brand
     [popperTarget]="brand"
     [hcPopover]="appSwitcherContent"
     popperPlacement="bottom-start"
     [className]="brandBg"
     (popperOnShown)="buttonOn()"
     (popperOnHidden)="buttonOff()">
    <img src="./assets/TriFlame.svg">
</div>
```

**Expected behavior**
I would expect this to be configurable by the user, similarly to how the navbar works. Perhaps it can be provided by the navbar that is hosting this switcher?

**Comment by jtrujill** [comment] 2018-06-22 16:22
I had made a previous [comment](https://github.com/HealthCatalyst/Fabric.Cashmere/issues/280#issuecomment-399493560) about this that I believe would also solve this. Also I guess I'm a bit confused with how this currently works. Looking at the [navbar](https://cashmere.healthcatalyst.net/components/navbar) it looks like you can provide your own icon on the left side but the appswitcher looks like it provides the same icon.

For a library we can't really provide our own assets like this. We could bundle the assets into the package that gets uploaded to NPM but then you would require that the user manually move those files into their asset directory. This isn't an easy or reliable solution for users of the library so instead we need to allow them to provide the assets

**Comment by andrew-frueh** [comment] 2018-08-12 18:11
duplicate of #439

**Closed by andrew-frueh** 2018-08-12 18:11 UTC
