### ISSUE TITLE
An error message is not displayed when an invalid year (e.g. 201444) is entered in the start date field

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#750] opened 2019-02-26 15:45 UTC
1. Go to the Explore tab
2. Open the custom date range
3. Remove the end date
4. Add one numeric value to the end of the start date year
5. Click on the end date field
6. Add another numeric value to the end of the start date year
7. Click on the end date field again

**Screenshots**
![image](https://user-images.githubusercontent.com/1934453/53425752-d7d42300-39a2-11e9-9e89-002c680a47f3.png)

**Comment by lindachan465** [comment] 2019-07-31 23:43
There's a general date validation issue on all date fields - I can put in random words, symbols, and numbers, and there is no validation that the format is incorrect.

**Comment by andrew-frueh** [comment] 2019-09-28 02:46
@benjanderson - I'm not able to reproduce this error on the Cashmere example:
https://cashmere.healthcatalyst.net/components/date-range/examples

Was it addressed in another pull request that didn't close this issue?

**Comment by andrew-frueh** [comment] 2019-09-28 02:50
Looks like #748 is where this was fixed.  Closing the issue.

**Closed by andrew-frueh** 2019-09-28 02:50 UTC
Labels: bug, validation
