### ISSUE TITLE
File Upload/Attachment Styles

### ISSUE THREAD

**Issue by cikeddy** [HealthCatalyst/Fabric.Cashmere#2023] opened 2022-12-21 18:12 UTC
**Describe your idea**
A section in additional styles for file uploads.

**What problem are you trying to solve?**
Provide a standard format for file uploads.

**Additional context**
![image](https://user-images.githubusercontent.com/46426253/208974988-82009c59-c0e8-40b9-b15c-f5fbae64fef9.png)

**Comment by andrew-frueh** [comment] 2023-01-27 20:39
Duplicate of #592 - referenced the above design there.

**Closed by andrew-frueh** 2023-01-27 20:39 UTC
