### ISSUE TITLE
Advanced Filters Guide

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#157] opened 2018-03-01 04:30 UTC
Create a section for our soon-to-be-added "Guides" section related to including "Advanced Filters" within an app.  This is a common usage pattern seen in several of our apps, and it would be created using a combination of several Cashmere components including `hc-chips`, `hc-drawer`, and `hc-list`.  This guide would provide a blueprint for how to leverage these components to recreate this functionality in a standardized way.

![35576384-12dee732-059c-11e8-9404-24b3cfef970a](https://user-images.githubusercontent.com/22795893/36827056-72bf94fa-1cce-11e8-8585-b2e1e7fb57e3.png)

**Comment by jtrujill** [comment] 2018-08-12 00:43
Duplicate of #411

**Closed by jtrujill** 2018-08-12 00:43 UTC
