### ISSUE TITLE
hc-select doesn't properly implement [ngValue]

### ISSUE THREAD

**Issue by AdamGMiller** [HealthCatalyst/Fabric.Cashmere#969] opened 2019-09-04 23:31 UTC
**Summary**

When using [ngValue] with hc-select, only the option text and not the full object is passed to the form value.

For example, when getting the value of the selected state:
```
states = [
    {name: 'Arizona', abbrev: 'AZ'},
    {name: 'California', abbrev: 'CA'},
  ];
(snip)
  <hc-form-field>
    <hc-label>HC Select: (using [ngValue])</hc-label>
    <hc-select placeholder="Select a state:" formControlName="hcState">
      <option *ngFor="let state of states" [ngValue]="state">
        {{ state.name }}
      </option>
    </hc-select>
  </hc-form-field>
```

The value of the form will be the name of the state and not the full `state` object as expected.

**Reproduction**
Stackblitz reproduction:
[https://stackblitz.com/edit/angular-ahovbk](https://stackblitz.com/edit/angular-ahovbk)

**Comment by andrew-frueh** [comment] 2019-09-04 23:35
Hey Adam - I believe this might be a duplicate of #779 .  Which is definitely something @joeskeen has identified as a high priority fix.  Can you double check if we're talking about the same thing?

**Comment by joeskeen** [comment] 2019-09-04 23:39
Agreed, this does look like a dupe of #779 and #963 ... so the fact that this comes up constantly is a strong signal that this should be the next bug I fix for sure ;)

@AdamGMiller I'm going to close this; could you please add any other information you feel is relevant to #779 ?

**Closed by joeskeen** 2019-09-04 23:39 UTC
