### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Cashmere#260] opened 2018-05-21 15:59 UTC
Create an issue template according to @isaaclyman 's comments in #72 

> A common practice on GitHub repos is that before an individual contributor (i.e. not an official project maintainer) writes any code, they create an issue detailing their intentions (a design document). It includes:
>
> - Why a change is needed
> - Whether it's a bug fix or a new feature
> - Which files are going to be modified
> - Which public interfaces will have to change, and how
>
>This doesn't need to take longer than a couple minutes, and we can make it easy by using GitHub issue templates. Then a maintainer adds a tag to the issue (to the effect of go-ahead), the fix or feature is implemented, and a pull request is submitted. If we keep the issue template small and explain the process in a root-level CONTRIBUTING.md or in the README, it shouldn't create too much friction for newcomers, especially if you're really hands-on about explaining the process and being helpful.
>
> I'm all for inclusivity and low barriers to entry, but this library needs to be predictable and mature if the whole company is going to use it. The only way to get there is with a process that ensures all changes are planned out ahead of time and well-vetted before merging.

**Comment by benjanderson** [comment] 2018-05-30 18:34
I love this idea, I would just add one more thing and if it is at all possible they could reproduce the issue by forking this stackblitz: https://stackblitz.com/edit/cashmere-demo?file=app%2Fhome%2Fhome.component.html

I have been maintaining this stackblitz and it has been excellent in being close to the desktop environment

If anyone has any concerns let me know because I would be willing to spearhead this, I am assigning it to myself

**Closed** 2018-06-06 17:33 UTC
