### ISSUE TITLE
css class naming

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#84] opened 2018-02-01 18:35 UTC
Wondering if we need to think about a standard naming system for our css, and if we do, my first idea is to use BEM:[http://getbem.com/naming/](url)  Anyone else have thoughts on this topic?

**Comment by jtrujill** [comment] 2018-02-03 15:41
I actually like this idea. This is something that i've started to pick up in this project. For example, in the list component the outside element has a class of hc-list and there are 4 subcomponents and directives that belong to the list component.

hc-list-item, hcListAvatar, hcListIcon, hcListIcon all of which have the following classes: hc-list-item, hc-list-avatar, hc-list-icon, hc-list-icon. I didn't need to create any more classes than this but if I had, I would have appended a modifier to the end of the classes above. In addition to the BEM idea i've scoped my class names to hc to further namespace my components class names. 

The only real problem I have with the BEM style of naming your classes is the double hyphen. It's mostly subjective, but I prefer single hyphens.

**Comment by jacquie** [comment] 2018-02-03 16:51
I agree that the double hyphens are ugly and a pain to type, but the reasoning is that you would use a single hyphen to replace spaces in multi-word names (kebab-case) eg we have a class 'green-arrow-up'. 

How about if we use a single _ to add a modifier instead of --? Eg 'block__elem_multi-word-mod' .
For me (being a bear of very little brain) that also seems more straightforward than having to remember when to use __ or --  :)

**Comment by ckeates** [comment] 2018-02-05 18:46
Great discussion to get started, Jacquie.  

I still feel fairly outclassed (🙄) about all of the different styling methodologies...but I did find this article:
https://medium.com/actualize-network/modern-css-explained-for-dinosaurs-5226febe3525

And eventually led me to this blog post about "rethinking BEM with Angular":
http://www.thatguyjackguy.com/tech/web-component-styling/

Obviously anecdotal, but the author raises some interesting points about leveraging Angular/Shadow-DOM-ish stuff, like Input decorators and parent selectors, to encapsulate styling without lots of modifier classes.  This is me playing devils' advocate, I don't feel like I quite grasp the absolute pros/cons of going with this over something else!

**Comment by corykon** [comment] 2018-02-06 15:53
Good articles 👍 Based on what I read there, and my own experience in angular apps, it seems like when things are properly componentized and encapsulated, you actually don't need to use as many css classes as youwould otherwise, so all the dashes and underscores feel like they might be overkill.

On the other hand, I've heard from a lot of people who champion the BEM methodology, so I may just need to understand it better, and am certainly open to learning it!

**Comment by jtrujill** [comment] 2018-08-12 00:38
Duplicate of #411

**Closed by jtrujill** 2018-08-12 00:38 UTC
Labels: discussion
