### ISSUE TITLE
Feedback blocks

### ISSUE THREAD

**Issue by cedar-ave** [HealthCatalyst/Fabric.Cashmere#329] opened 2018-06-15 16:22 UTC
There is a need on a team for an alert that lights up when users are using the application in a non-optimal way (that is not a pop-up requiring an extra click to close) -- something like:

![2018-06-15 10_21_00-adobe xd cc](https://user-images.githubusercontent.com/15255009/41478702-ed4fd8b4-7085-11e8-82d3-2b516f32e5c9.png)

This is an example on MailChimp's style guide:

![2018-06-15 10_20_03-feedback _ mailchimp](https://user-images.githubusercontent.com/15255009/41478709-f522e0a4-7085-11e8-82a6-75d18901ec23.png)

[http://ux.mailchimp.com/patterns/feedback](http://ux.mailchimp.com/patterns/feedback)

Sorry if I missed something in the style guide that already exists -- the closest I can see are the alert chips. Thank you!

**Comment by jtrujill** [comment] 2018-06-15 16:52
After taking a look at the documentation maybe it'd be good to allow more freedom with the component so that you can provide you own custom icon. It would be easy to allow the user to add styling or background and foreground color. 

Also maybe it'd be good to allow them to easily have a multi-line chip like shown above. Again that should be easy to do. @andrew-frueh what do you think of that idea? I think multi-line would be valuable and would only require one new directive and a slight alteration to the component styling.

I think the only thing is that whether it has one or 2 lines all chips should be the same height

**Comment by jtrujill** [comment] 2018-06-15 17:18
Another thing what do you think about changing the chips from using a color property to a type property so that you can use more descriptive names for what the chip is, such as: warning, error, info, success

**Comment by andrew-frueh** [comment] 2018-08-21 21:01
@corykon I believe this is a duplicate of #175.  Would you agree or do you consider these message blocks something separate?

**Comment by jtrujill** [comment] 2018-08-21 21:06
I believe this is something different. I believe this is meant as a notification that appears to the is at the top and requires them to open it or hit the x to dismiss it. While toasts sit outside the flow of the Dom and are quick notifications

**Comment by andrew-frueh** [comment] 2018-08-21 21:12
It's interesting, I should have looked closer at the MailChimp page @cedar-ave referenced.  On there they lump all those elements together into a page called "Feedback Elements", which they subdivide into:

- **Flash Blocks**: provide action-based feedback messages or to convey informational and/or critical account-related messages.
- **Badges**: basically the same as our chips
- **Toaster Messages**: toaster messages are shown at the bottom-left of the page and stay for ~2 seconds, providing immediate feedback in response to a user action.
- **Callout tips**: kind of like a flash block with a light bulb icon
- **Progress dots**: not really sure why they included these in this section

So yes, they definitely appear to be different but related things.  When we consider tackling this, we should make sure the look and feel is aligned with #175 and chips.

**Closed** 2018-12-11 00:43 UTC
Labels: enhancement
